-- SQL View for CIB Offer Letter Notices Contact Grid
-- Maps to  : CLOS_CIB_Offer_Letter_NOTICES_GRID.xml (GRIDFIELDS: DBCOLNAME/MAPCOLNAME)
-- Registered: DBTABLENAME in CLOS_CIB_Offer_Letter_ListView.xml
-- Source Table: CLOS_route_table

CREATE OR REPLACE VIEW CLOS_NOTICES_GRID_VW AS
SELECT
    CONTACT_NAME AS CONTACT_NAME,
    CONTACT_TITLE AS CONTACT_TITLE,
    CONTACT_ADDRESS AS CONTACT_ADDRESS,
    CONTACT_EMAIL AS CONTACT_EMAIL,
    CONTACT_PHONE AS CONTACT_PHONE
FROM CLOS_route_table;