-- SQL View for CIB Offer Letter Facility Grid
-- Maps to  : CLOS_CIB_Offer_Letter_FACILITY_GRID.xml (GRIDFIELDS: DBCOLNAME/MAPCOLNAME)
-- Registered: DBTABLENAME in CLOS_CIB_Offer_Letter_ListView.xml
-- Source Table: CLOS_route_table

CREATE OR REPLACE VIEW CLOS_FACILITY_GRID_VW AS
SELECT
    FACILITY_TYPE AS FACILITY_TYPE,
    FACILITY_AMOUNT AS FACILITY_AMOUNT,
    PURPOSE_OF_FACILITY AS PURPOSE_OF_FACILITY,
    TENOR AS TENOR,
    INTEREST_RATE AS INTEREST_RATE,
    ARRANGEMENT_FEES AS ARRANGEMENT_FEES,
    MONTHLY_REPAYMENT AS MONTHLY_REPAYMENT,
    OTHER_FEES AS OTHER_FEES
FROM CLOS_route_table;