-- SQL View for CIB Offer Letter individual variable fields
-- Maps to  : CLOS_CIB_Offer_Letter_MAIN.xml (FIELDS: EXTNAME/TEMPNAME)
-- Referenced: EXTTABLENAME in CLOS_CIB_Offer_Letter.properties
-- Source Table: CLOS_route_table

CREATE OR REPLACE VIEW CLOS_CIB_OFFER_LETTER_VW AS
SELECT
    LOS_REF_NO AS LOS_REF_NO,
    OFFER_DATE AS OFFER_DATE,
    BORROWER_NAME AS BORROWER_NAME,
    ADDRESS_LINE1 AS ADDRESS_LINE1,
    ADDRESS_LINE2 AS ADDRESS_LINE2,
    ADDRESS_LINE3 AS ADDRESS_LINE3,
    FACILITY_SUBTYPE AS FACILITY_SUBTYPE,
    INTEREST_RATE AS INTEREST_RATE,
    USD_LENDING_RATE AS USD_LENDING_RATE,
    DEFAULT_INTEREST_RATE AS DEFAULT_INTEREST_RATE,
    FINANCIAL_PERIOD AS FINANCIAL_PERIOD,
    PROPERTY_COMPRISED AS PROPERTY_COMPRISED,
    PROPERTY_INO AS PROPERTY_INO,
    BANK_SIGNATORY1_NAME AS BANK_SIGNATORY1_NAME,
    BANK_SIGNATORY1_TITLE AS BANK_SIGNATORY1_TITLE,
    BANK_SIGNATORY2_NAME AS BANK_SIGNATORY2_NAME,
    BANK_SIGNATORY2_TITLE AS BANK_SIGNATORY2_TITLE,
    INDEPENDENT_ADVISOR_NAME AS INDEPENDENT_ADVISOR_NAME,
    INDEPENDENT_ADVISOR_ROLE AS INDEPENDENT_ADVISOR_ROLE,
    DECLARANT_NAME AS DECLARANT_NAME,
    DECLARATION_DAY AS DECLARATION_DAY,
    DECLARATION_MONTH AS DECLARATION_MONTH,
    ILLITERATE_WITNESS_NAME AS ILLITERATE_WITNESS_NAME,
    ILLITERATE_NAME AS ILLITERATE_NAME,
    BANK_OFFICER_NAME AS BANK_OFFICER_NAME,
    BANK_OFFICER_DESIGNATION AS BANK_OFFICER_DESIGNATION,
    ILLITERATE_LANGUAGE AS ILLITERATE_LANGUAGE,
    SIGN_DAY AS SIGN_DAY,
    SIGN_MONTH AS SIGN_MONTH,
    SIGN_YEAR AS SIGN_YEAR
FROM CLOS_route_table;