
 CREATE OR REPLACE FORCE EDITIONABLE VIEW "RW_CLOS_VEHICLE_FINCN_MAIN_VW" 
 ("WORKITEM_NAME", "PROPOSAL_NO", "OMV", "ACC_PERFORMANCE_GRID", "SALES_PROFITABITY", "FSV", "TOTAL_CHARGE") AS 
  SELECT    
    WORKITEM_NAME,
    PROPOSAL_NO,        
    TO_CHAR(OMV, '999,999,999,999') AS OMV,
    ACC_PERFORMANCE_GRID,
    SALES_PROFITABITY,
    TO_CHAR(FSV, '999,999,999,999') AS FSV,
    TO_CHAR(TOTAL_CHARGE, '999,999,999,999') AS TOTAL_CHARGE
FROM RW_CLOS_VEHICLE_FINCN_APPLICATION_FORM; 

